platform: linux
image_resource:
  type: docker-image
  source:
    repository: odpks/pks-ci

inputs:
  - name: pool-pks-locks
  - name: git-kubo-odb-ci
  - name: git-boshcycle-ci
  - name: stemcell
  - name: gcs-director-config

params:
  DEPLOYMENT_NAME: "SOME_DEFAULT_DEPLOYMENT"

run:
  path: git-boshcycle-ci/ci/tasks/upload-stemcell/task.sh
