platform: linux
image_resource:
  type: docker-image
  source:
    repository: odpks/pks-ci

inputs:
  - name: git-boshcycle-ci
  - name: bosh-release

run:
  path: git-boshcycle-ci/ci/minimum-release-verification/tasks/run-tests/task.sh
