platform: linux
image_resource:
  type: docker-image
  source:
    repository: odpks/pks-ci

inputs:
  - name: git-pks-kubernetes-release-ci
  - name: bosh-release

run:
  path: git-pks-kubernetes-release-ci/ci/tasks/run-tests/task.sh
